language: python
dist: trusty
sudo: required
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7-dev"
 - "pypy-5.4"
 - "pypy3.3-5.2-alpha1"

branches:
  only:
    - master

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"
  - pip install pybuilder
  - pyb install_dependencies
  - sudo apt-get install pychecker

script:
  - pyb

env:
  global:
    - PATH="${PATH}:$HOME/bin"
    - SLIPWAY_VERSION=0.2.17

notifications:
  email:
    recipients:
      - ugochukwu.enyioha@one.verizon.net
    on_success: change
    on_failure: always
