language: python
dist: trusty

python:
  - "3.6"
  - "2.6"
  - pypy-5.4.1
  - "2.7"
  - "3.5"

branches:
  only:
    - master

install:
  - wget http://nexus.oncue.verizon.net/nexus/content/repositories/releases/verizon/inf/slipway/${SLIPWAY_VERSION}/slipway-linux-amd64-${SLIPWAY_VERSION}.tar.gz -O slipway.tar.gz
  - tar xvf slipway.tar.gz
  - mkdir $HOME/bin && mv slipway $HOME/bin/slipway

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"
  - pip install pybuilder
  - pyb install_dependencies
  - sudo apt-get install pychecker

script:
  - pyb

env:
  global:
    - PATH="${PATH}:$HOME/bin"
    - SLIPWAY_VERSION=0.2.17

notifications:
  email:
    recipients:
      - ugochukwu.enyioha@one.verizon.net
    on_success: change
    on_failure: always
