language: python

python:
  - "2.7"
  - pypy

branches:
  only:
    - master

install:
  - wget http://nexus.oncue.verizon.net/nexus/content/repositories/releases/verizon/inf/slipway/${SLIPWAY_VERSION}/slipway-linux-amd64-${SLIPWAY_VERSION}.tar.gz -O slipway.tar.gz
  - tar xvf slipway.tar.gz
  - mkdir $HOME/bin && mv slipway $HOME/bin/slipway

before_script:
  - "if [ $TRAVIS_PULL_REQUEST = 'false' ]; then git checkout -qf $TRAVIS_BRANCH; fi"
  - pip install pybuilder
  - pyb install_dependencies
  - sudo apt-get install pychecker

script:
  - pyb

env:
  global:
    - PATH="${PATH}:$HOME/bin"
    - SLIPWAY_VERSION=0.2.17
    - secure: "R+kEGCclEe9W9VbtGK4wFyDNz8x4bBcbzClyGTS4tHuthjb1cBifpL1gJYuNd6mQh2IvbsFgBvn1HKuhR73TrUZItwIRu9WEWeDMiZfXWYdyA0znc4trGn3Rya8mCp+V0EBnqNnHygyFuqjacUV1FOo5XxzPyQ8iPTm8t7uHqQ0clYcOq3zYNvMH7myxnNiFqeZZUgxv/JBVMcDslfq4Xk+GdCzdBmIUXeVJcSba12zRNPFr1gYAwucznVEPyUD2dmB/xm5uFA6nqeqekglclj2xyYDmSNs2qz6cYFs2cvJU7BM0HYL8132jK+g9AgplWmJ0QmVtbeoZyIjlckDnPop4aczscMuHErU+Btw6a4EKZdgYq/nL1erl1eQDmQ/AO1nqZFkyRIbcdQdTdGKN6xarZeaISYBAZ5kRO8pTtFbXKZTT91Dd3D+bHsKzr9Zvfmc6avex+tmg1wUJIKp6aJYS2iiTqqJt+SuG5fuVJxQEqTmLAZ5a7AjR4K2uIECDM/CsSAT89A2Pj+Y2sfsnZ8Z7Pe0qryEdMseA4Lub6PmFqsVZ+N+/yfnAYLqi+yR6mvHVtxwZbV31NJZ9mubRDFo/xtyTI6x3APHXrdthCvAZnIpzbNjQ3mvP3nkpCV9CTo+H2M/8W4zEczEfL6I1eFQnY/nXx6yUTpSMuTNf7Mc="

notifications:
  email:
    recipients:
      - ugochukwu.enyioha@one.verizon.net
    on_success: change
    on_failure: always
